service: moc-gen-server
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  memorySize: 1024 # repository wide Lambda memory size
  stage: prod
  timeout: 30 # repository wide Lambda timeout
  environment: # repository wide Lambda env variables
    NODE_ENV: production
  # Add this: (supports image)
  apiGateway:
    binaryMediaTypes:
      - "multipart/form-data"
      - "image/*"

plugins:
  - serverless-offline # used for local execution

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: []
    target: "node20" # Node.js version must match your runtime
    define: { "require.resolve": "undefined" }
    platform: "node"
    concurrency: 10

functions:
  app:
    handler: main.handler
    events:
      # Handle the root path ("/")
      - http:
          path: /
          method: any
          cors: true
      # Handle all other paths (catch-all "/{proxy+}")
      - http:
          path: /{proxy+}
          method: any
          cors: true